---
title: "Notas Prueba 1 (SOL114)"
author: "Mauricio Bucca"
format: html
editor: visual
---

## Notas

```{r, echo=F, message=FALSE, warning=FALSE}
library("pacman")
p_load(googlesheets4, tidyverse, kableExtra)

#gs4_auth()

sheet_url <- "https://docs.google.com/spreadsheets/d/1BFWZx0b44gvvfTgA337I30oJwiV09mkF3_bUTM-WepE/edit#gid=0"

notas_prueba1 <- gs4_get(sheet_url)

notas <- read_sheet(notas_prueba1, sheet= "Prueba 1")

data_grades <- notas %>% drop_na(Nota) %>% select(Rut,`1.i`:Nota) %>%  
  mutate(`P(Nota < tunota)` =rank(Nota)/n()) 

data_grades %>% knitr::kable(digits=2) %>% kable_styling(font_size = 9)

```

## Resumen estadístico

El siguiente gráfico muestra la distribución de las notas:

```{r, echo=F, message=FALSE, warning=FALSE}

# Compute statistical metrics
media <- mean(data_grades$Nota)
mediana <- median(data_grades$Nota)
sd <- sd(data_grades$Nota)
min_val <- min(data_grades$Nota)
max_val <- max(data_grades$Nota)

# Set limits for y-axis so the annotations have enough space
limits_y <- c(0, max(density(data_grades$Nota)$y)*1.5)

# Define ggplot
p <- ggplot(data_grades, aes(x = Nota)) +
  geom_histogram(aes(y = ..density..), 
                 fill = "blue", 
                 alpha = 0.5, 
                 bins = 30) +
  geom_density(fill = "red", alpha = 0.3) +
  geom_vline(xintercept = media, linetype = "dashed", color = "black") +
  geom_text(aes(x = 1.1, y = limits_y[2] * 0.9, 
                label = paste("Media =", round(media, 2))), hjust = 0) +
  geom_text(aes(x = 1.1, y = limits_y[2] * 0.8, 
                label = paste("Min =", round(min_val, 2))), hjust = 0) +
  geom_text(aes(x = 1.1, y = limits_y[2] * 0.7, 
                label = paste("Max =", round(max_val, 2))), hjust = 0) +
  geom_text(aes(x = 1.1, y = limits_y[2] * 0.6, 
                label = paste("SD =", round(sd, 2))), hjust = 0) +
  labs(title = "Distribución of Notas",
       x = "Nota",
       y = "Densi") +
  xlim(1,8) +
  theme_minimal() +
  coord_cartesian(ylim = limits_y)

# Display plot
print(p)


```

Desagregando por pregunta:

```{r, echo=F, message=FALSE, warning=FALSE}

# Loading necessary libraries
library(ggridges)

# Data preparation
data_long <- data_grades %>%  select(Rut,`1.i`:`5.v`) %>%
  pivot_longer(cols = `1.i`:`5.v`, names_to = "Variable", values_to = "Value")

# Calculate means for annotations
data_long %>%
  group_by(Variable) %>%
  summarise(Promedio = mean(Value, na.rm = TRUE),
            Min = min(Value, na.rm = TRUE),
            Max = max(Value, na.rm = TRUE),
            SD = sd(Value, na.rm = TRUE)
            ) %>% 
  knitr::kable(digits=2) %>% kable_styling(font_size = 9)
  



```
