---
title: "Tarea corta #1"
author: "SOL114"
format: html
editor: visual
---

```{r, echo=FALSE}
# Escribir install.packages("tinytex") en la consola para instalar "tinytex"
# Carga "tinytex" para compilar PDF
library("tinytex")
```

`Ponderación: 5% de la nota final del curso.`

<br>

**1) Exponenciales y Logaritmos**

a)  Simplifica: $(4^3) \times (4^2)$

<!-- -->

b.  Resuelve por x: $2^{x} = 32$

<!-- -->

c)  Simplifica: $\frac{e^{6x}}{e^{2x}}$

d)  Simplifica: $\ln(x) + \ln(y)$

e)  Simplifica: $\ln(b^3)$

<br>

**2) Sumatoria**

Calcula la sumatoria de $(c \cdot i + d)$ desde $i = 1$ hasta $5$.

<br>

**3) Derivadas**

a)  Calcula la derivada de la siguiente función: $f(x) = 7x^4 - 5x^3 + 2x - 8$

<br>

b)  Dada la función: $y = 4 + 3x^2$

```{=html}
<!-- -->
```
1.  Grafica la función.

2.  Identifica por inspección visual el valor de $x$ en que la función alcanza su mínimo.

3.  Determina el valor de la pendiente en ese punto.

<br>

**4) Aproximación discreta de integrales**

Aproxima la integral de $f(x) = x^3$ desde 1 hasta 3 usando 4 rectángulos. Específicamente: divide el intervalo desde 1 hasta 3 en 4 subintervalos de igual tamaño y luego evalúa la función en el punto más a la izquierda de cada subintervalo. Ejemplo, para el intervalo entre 1.5 y 2 usa el valor $x = 1.5$, y por tanto $f(x) = f(1.5)$.

<br>

**5) Integral definida**

Evalúa la integral: $\int_{1}^{3} x^3 \, dx$
