---
title: "Tarea corta #2, respuestas"
author: "SOL114"
format: html
editor: visual
---

```{r, echo=FALSE}
# Escribir install.packages("tinytex") en la consola para instalar "tinytex"
# Carga "tinytex" para compilar PDF
library("tinytex")
```

`Ponderación: 6% de la nota final del curso.`

La variable aleatoria discreta $X$ representa el nivel de educación alcanzado por los egresados de un colegio. Para dicho colegio sabemos lo siguiente:

1.  El 30% de los estudiantes decide no ir a la universidad.

2.  El 70% de los estudiantes decide ir a la universidad.

    De los estudiantes que van a la universidad:

    -   El 80% termina sus estudios universitarios.
    -   El 20% no termina sus estudios universitarios.

Definimos la variable Aleatoria $X$ del siguiente modo:

-   $X = 0$: El estudiante no va a la universidad.
-   $X = 1$: El estudiante va a la universidad pero no termina sus estudios.
-   $X = 2$: El estudiante va a la universidad y termina sus estudios.

### Ejercicios:

1.  Formaliza la Distribución de Probabilidad:
    -   Usando la descripción de la variable $X$, formaliza la distribución de probabilidad para $X$. Asegúrate de que la suma de todas las probabilidades sea igual a 1.

> **Solución:**
>
> $$P(X = 0) = 0.30$$ $$P(X = 1) = 0.70 \times 0.20 = 0.14$$ $$P(X = 2) = 0.70 \times 0.80 = 0.56$$
>
> Verificación:
>
> $$\sum_{i=0}^{2} P(X = i) = P(X = 0) + P(X = 1) + P(X = 2) = 0.30 + 0.14 + 0.56 = 1$$

2.  Si la mitad de los egresados de este colegio son hombres y la otra mitad mujeres, y el logro educacional es independiente del género de los egresados, calcula:
    -   La probabilidad de que un egresado del colegio sea una mujer que nunca fue a la universidad.
    -   La probabilidad de no haber ido a la universidad para un egresado hombre (condicional).

> **Solución:**
>
> -   Probabilidad de que un egresado sea una mujer que nunca fue a la universidad. Dado que la mitad de los egresados son mujeres:
>
> $$P(\text{mujer y } X = 0) = P(\text{mujer}) \times P(X = 0) = 0.50 \times 0.30 = 0.15$$
>
> -   Probabilidad de no haber ido a la universidad para un egresado hombre. Dado que el logro educacional es independiente del género:
>
> $$P(X = 0 \mid \text{hombre}) = P(X = 0) = 0.30$$
