---
title: "SOL114 Análisis de Datos II"
author: "Tarea corta 6"
format: html
editor: visual
---


## Problema:

En esta tarea usarás los datos de una encuesta realizada por FLACSO/Chile en Abril y Mayo de 1988 sobre intención de voto en el plebiscito de 1989, junto con otras variables socio-demográficas. Las variables son las siguientes:

-   `región`: Un factor con niveles: C, Central; M, Área Metropolitana de Santiago; N, Norte; S, Sur; SA, ciudad de Santiago.

-   `población`: Tamaño de la población de la comunidad del encuestado.

-   `sexo`: Un factor con niveles: F, femenino; M, masculino.

-   `edad`: En años.

-   `educación`: Un factor con niveles (nota: fuera de orden): P, Primaria; PS, Post-secundaria; S, Secundaria.

-   `ingreso`: Ingreso mensual, en Pesos.

-   `statusquo`: Escala de apoyo al status quo (apoyo a régimen de Pinochet).

-   `voto`: Un factor con niveles: A, se abstendrá; N, votará no (en contra de Pinochet); U, indeciso; Y, votará sí (a favor de Pinochet).

1.  Usa un test de permutaciones para testear la hipótesis de que, en promedio, las mujeres muestran mayor apoyo al regimen de Pinochet que los hombres.

```{r, message=FALSE, warning=FALSE}
options(scipen = 999)
library(carData)
library(tidyverse)

datos_chile <- carData::Chile


# estimacion de apoyo al statusquo por género

resultados <- datos_chile %>%
    group_by(sex) %>% 
    summarise(mu_statusquo = mean(statusquo, na.rm = T)) %>%
    pull(mu_statusquo)

diferencia <- resultados[1] - resultados[2]
print(diferencia)

# # # # # # # # # # # # # # # # # # # #  TEST PERMUTACIONES # # # # # # # # # # # # # # # # # # # # # # 


# n data

n <- datos_chile %>% nrow() 


# define función permutación
permutaciones <- function() {
  
index <- sample(1:n, size=n, replace=FALSE)

resultados_perm <- datos_chile %>% mutate(statusquo_perm = statusquo[index]) %>%
    group_by(sex) %>% 
    summarise(mu_statusquo_perm = mean(statusquo_perm, na.rm = T))  %>% pull(mu_statusquo_perm)
    return( resultados_perm[1] -  resultados_perm[2])
}

# aplica la funcion 5 mil veces y guarda resultados

dif_permut <- replicate(n=5000, expr = permutaciones())

# p-value: % de diferencias permutadas que se encuentran por sobre el valor del estadístico obtenido


p_value_perm = mean(dif_permut>diferencia)

```
