---
title: "Nota Final (SOL114)"
author: "Mauricio Bucca"
format: html
editor: visual
---

## Notas

```{r, echo=F, message=FALSE, warning=FALSE}
library("pacman")
p_load(googlesheets4, tidyverse, kableExtra,mclust)


sheet_url_1 <- "https://docs.google.com/spreadsheets/d/1BFWZx0b44gvvfTgA337I30oJwiV09mkF3_bUTM-WepE/edit#gid=1064220691"

sheet_url_2 <- "https://docs.google.com/spreadsheets/d/1BFWZx0b44gvvfTgA337I30oJwiV09mkF3_bUTM-WepE/edit#gid=1548544822"

sheet_url_3 <- "https://docs.google.com/spreadsheets/d/1BFWZx0b44gvvfTgA337I30oJwiV09mkF3_bUTM-WepE/edit#gid=1078351516"

sheet_url_4 <- "https://docs.google.com/spreadsheets/d/1BFWZx0b44gvvfTgA337I30oJwiV09mkF3_bUTM-WepE/edit#gid=1652049220"

sheet_url_5 <- "https://docs.google.com/spreadsheets/d/1BFWZx0b44gvvfTgA337I30oJwiV09mkF3_bUTM-WepE/edit#gid=588136254"

notas_prueba1 <- gs4_get(sheet_url_1)
notas_prueba2 <- gs4_get(sheet_url_2)
notas_bonus  <-  gs4_get(sheet_url_3)
notas_tareas  <- gs4_get(sheet_url_4)
notas_examen  <- gs4_get(sheet_url_5)


notas_prueba1 <- read_sheet(notas_prueba1, sheet= "Prueba 1")
notas_prueba2 <- read_sheet(notas_prueba2, sheet= "Prueba 2")
notas_bonus   <- read_sheet(notas_bonus, sheet= "Prueba Bonus")
notas_tareas  <- read_sheet(notas_tareas, sheet= "Tareas")
notas_examen  <- read_sheet(notas_examen, sheet= "Examen")


notas_prueba1 <- notas_prueba1 %>% rename(nota_prueba1 = Nota)
notas_prueba2 <- notas_prueba2 %>% rename(nota_prueba2 = Nota)
notas_bonus   <- notas_bonus   %>% rename(nota_bonus = Nota)
notas_tareas  <- notas_tareas   %>% rename(nota_tareas = tarea_promedio)

notas_examen  <- notas_examen   %>% rename(nota_examen = Nota) %>% 
  mutate(nota_examen = if_else(nota_examen>7,7,nota_examen), nota_examen = round(nota_examen,1))

notas_finales <- notas_prueba1 %>% select(1:5,nota_prueba1) %>% 
  left_join(notas_prueba2 %>% select(Rut,nota_prueba2), by="Rut") %>%
  left_join(notas_bonus %>% select(Rut,nota_bonus), by="Rut") %>%
  left_join(notas_tareas %>% select(Rut,nota_tareas), by="Rut") %>%
  left_join(notas_examen %>% select(Rut,nota_examen), by="Rut") 

```

```{r, echo=F, message=FALSE, warning=FALSE}

# casos con una prueba faltante 

notas_finales <- notas_finales %>% replace_na(list(nota_bonus = 1))
  
notas_finales <- notas_finales %>%  mutate(missing_pruebas = 1*is.na(nota_prueba1) + 1*is.na(nota_prueba2)) 

notas_finales <- notas_finales %>% 
  mutate(nota_prueba1 = if_else(missing_pruebas ==1 & is.na(nota_prueba1), 
                                nota_bonus,nota_prueba1))

notas_finales <- notas_finales %>% 
  mutate(nota_prueba2 = if_else(missing_pruebas ==1 & is.na(nota_prueba2), 
                                nota_bonus,nota_prueba2))

notas_finales <- notas_finales %>%  mutate(missing_pruebas = 1*is.na(nota_prueba1) + 1*is.na(nota_prueba2))

notas_finales <- notas_finales %>%
  mutate(across(starts_with("nota_"), ~ replace_na(.x, 1))) %>%
  mutate(
    promedio_pruebas = if_else(
      rowMeans(select(., nota_prueba1, nota_prueba2), na.rm = TRUE) < nota_bonus,
      rowMeans(select(., nota_prueba1, nota_prueba2, nota_bonus), na.rm = TRUE),
      rowMeans(select(., nota_prueba1, nota_prueba2), na.rm = TRUE)
    ),
    nota_final = 0.3 * nota_tareas + 0.4 * promedio_pruebas + 0.3 * nota_examen
  )

notas_finales %>% drop_na(Rut) %>% 
  filter(nota_examen > 0) %>%
  mutate(nota_final = if_else(nota_final>=3.85 & nota_final<4,4,nota_final)) %>%
  select(Rut, nota_tareas,promedio_pruebas,nota_examen,nota_final) %>%
  rename(`Nota Final` = nota_final) %>%
  mutate(`P(Nota Final < tunota)` =rank(`Nota Final`)/n()) %>%
  knitr::kable(digits=c(0,1,1,1,1,2)) %>% kable_styling(font_size = 9)
```

## Resumen estadístico

El siguiente gráfico muestra la distribución de las notas:

```{r, echo=F, message=FALSE, warning=FALSE}

# Compute statistical metrics

notas_finales <- notas_finales %>% drop_na(nota_final)  %>%  filter(nota_examen > 0)

media <- mean(notas_finales$nota_final)
mediana <- median(notas_finales$nota_final)
sd <- sd(notas_finales$nota_final)
min_val <- min(notas_finales$nota_final)
max_val <- max(notas_finales$nota_final)

# Set limits for y-axis so the annotations have enough space
limits_y <- c(0, max(density(notas_finales$nota_final)$y)*1.5)

# Define ggplot
p <- ggplot(notas_finales, aes(x = nota_final)) +
  geom_histogram(aes(y = ..density..), 
                 fill = "blue", 
                 alpha = 0.5, 
                 bins = 30) +
  geom_vline(xintercept = media, linetype = "dashed", color = "black") +
  geom_text(aes(x = 1.1, y = limits_y[2] * 0.9, 
                label = paste("Media =", round(media, 1))), hjust = 0) +
  geom_text(aes(x = 1.1, y = limits_y[2] * 0.8, 
                label = paste("Min =", round(min_val, 1))), hjust = 0) +
  geom_text(aes(x = 1.1, y = limits_y[2] * 0.7, 
                label = paste("Max =", round(max_val, 1))), hjust = 0) +
  geom_text(aes(x = 1.1, y = limits_y[2] * 0.6, 
                label = paste("SD =", round(sd, 1))), hjust = 0) +
  labs(title = "Distribución de Notas**",
       x = "Nota",
       y = "Densidad") +
  xlim(1,8) +
  theme_minimal() +
  coord_cartesian(ylim = limits_y)

# Display plot
print(p)
```

## Pedestal de Honor

```{r, echo=F, message=FALSE, warning=FALSE}

notas_finales %>% drop_na(Rut) %>% 
  select(c(5,3),nota_final) %>%
  rename(`Nota Final` = nota_final) %>%
  arrange(desc(`Nota Final`)) %>%
  head(7) %>%
  knitr::kable(digits=1) %>% kable_styling(font_size = 9)

```
