---
title: "_________________________________________"
author: "Prueba 2 (recuperativa) SOL114"
format: pdf
editor: visual
mainfont: "Trixie-Text"
monofont: "Trixie-Text"
sansfont: "Trixie-Text"
geometry:
  - left=.5in
  - textwidth=5.5in
  - marginparsep=.25in
  - marginparwidth=2.25in
---

1. En una región conocida por su producción de manzanas de alta calidad, los agricultores han observado variaciones en el tamaño de las manzanas dependiendo de la variedad y las condiciones de cultivo. Específicamente, los expertos en agricultura han identificado que las manzanas de la variedad "Golden Delicious" tienen un tamaño que sigue una distribución normal con una media $\mu = 200$ gramos y una desviación estándar $\sigma = 20$ gramos. Un agricultor de la región tiene un huerto con 150 árboles de esta variedad y decide medir el tamaño promedio de las manzanas cosechadas ( $\bar{X}$ ). Después de realizar las mediciones, encuentra que el tamaño promedio es $\bar{X} = 195$ gramos.


i. Expresa la distribución muestral del tamaño promedio $\bar{X}$ de las manzanas y explica brevemente por qué el promedio muestral es aleatorio y no un parámetro fijo.

ii. Calcula un intervalo de confianza al 90% para el tamaño promedio estimado por el agricultor.

iii. En base a los resultados, ¿se puede afirmar que las manzanas de este huerto son estadísticamente más pequeñas, similares o más grandes en tamaño en comparación con el tamaño esperado para la variedad "Golden Delicious"?

\newpage

.
\newpage

2. Otro agricultor de la misma región decide investigar el tamaño promedio de las manzanas de la variedad "Golden Delicious" en su huerto. A diferencia de otros agricultores, no tiene conocimientos sobre la distribución poblacional del tamaño de estas manzanas. Por lo tanto, decide tomar una muestra de 10 manzanas y medir su peso para obtener una estimación. Los pesos de las manzanas (en gramos) de su muestra son los siguientes:

| Manzana $i$ | Peso  $x_i$ |
|-------------------|------------------|
| 1                 | 210              |
| 2                 | 205              |
| 3                 | 198              |
| 4                 | 202              |
| 5                 | 207              |
| 6                 | 211              |
| 7                 | 199              |
| 8                 | 204              |
| 9                 | 208              |
| 10                | 206              |
| **$\sum x_i$** | **2050** |
| **$\sum (x_i - \bar{x})^2$** | **110** |


i. Expresa la distribución muestral del tamaño promedio $\bar{X}$ de las manzanas de este agricultor.

ii. Calcula un intervalo de confianza al 90% para el tamaño promedio estimado por el agricultor.

iii. En base a los resultados, ¿se puede afirmar que las manzanas de este huerto son estadísticamente más pequeñas, similares o más grandes en tamaño en comparación con el tamaño esperado para la variedad "Golden Delicious"?

\newpage

.
\newpage

3. ¿Cuál es la probabilidad de que el peso promedio obtenido por el agricultor con una muestra de 10 manzanas sea menor que la media poblacional en al menos 5 gramos?

\newpage

4.  Una empresa de investigación de mercado, MarketInsight, lleva a cabo una encuesta en dos barrios, Sunnyside y Greenfield, para medir las preferencias de consumo entre dos productos: "Producto A" y "Producto B". En Sunnyside, los resultados sugieren una clara preferencia por el "Producto A", mientras que en Greenfield, "Producto B" parece ser más popular. A continuación, se presenta una tabla con los resultados de la encuesta para ambos barrios:

| Barrio    | Preferencia por "A" | Preferencia por "B" |
|-----------|------------------------------|------------------------------|
| Sunnyside | 120                          | 30                           |
| Greenfield| 40                           | 110                          |

i. Calcula la proporción estimada de individuos que prefieren el "Producto A" en cada barrio. 

ii. Construye un intervalo de confianza al 95% para la diferencia en las proporciones de preferencia por el "Producto A" entre los barrios Sunnyside y Greenfield

iii. Elabora una conclusión sustantiva en base a los resultados.

\newpage

.
\newpage

5.  La empresa MarketInsight decide aumentar la precisión de sus estudios de mercado. Contratan a un analista de datos para rediseñar el estudio sobre preferencias de consumo. Se le pide al analista que, trabajando con un 99% de confianza, reduzca el margen de error a 1 punto porcentual.

i.  Explica el concepto de márgen de error

ii. Calcula el tamaño muestral necesario para satisfacer la demanda presentada por la empresa y justifica tus decisiones metodológicas

\newpage


6.  Dado un estimador  $\hat{\theta}$ con varianza conocida $\sigma_{\hat{\theta}}$, formula el MSE e identifica una condición bajo la cual el sesgo de $\hat{\theta}$ es igual a cero. Explica en términos matemáticos y en palabras por qué esta condición es importante.