<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Prueba 2 SOL114">

<title>_________________________________________</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="prueba_2_answers_files/libs/clipboard/clipboard.min.js"></script>
<script src="prueba_2_answers_files/libs/quarto-html/quarto.js"></script>
<script src="prueba_2_answers_files/libs/quarto-html/popper.min.js"></script>
<script src="prueba_2_answers_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="prueba_2_answers_files/libs/quarto-html/anchor.min.js"></script>
<link href="prueba_2_answers_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="prueba_2_answers_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="prueba_2_answers_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="prueba_2_answers_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="prueba_2_answers_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">_________________________________________</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Prueba 2 SOL114 </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<p><strong>Problema I. (10%)</strong></p>
<p>La prueba <strong>PISA</strong> (Programa para la Evaluación Internacional de Estudiantes) es una evaluación global organizada por la <strong>OCDE</strong> que mide las competencias de los estudiantes de 15 años en tres áreas clave: <strong>lectura</strong>, <strong>matemáticas</strong> y <strong>ciencias</strong>. Esta evaluación se realiza cada tres años y busca proporcionar una visión comparativa del rendimiento educativo entre los países.</p>
<p>La siguiente tabla muestra los resultados en la prueba de <strong>matemáticas</strong> del último PISA 2022 para una submuestra de estudiantes de <strong>Chile</strong> y <strong>Dinamarca</strong>, segmentados por el nivel socioeconómico de los estudiantes. Los datos presentados incluyen los <strong>puntajes promedio</strong> y las <strong>desviaciones estándar</strong> para cada cuartil socioeconómico en ambos países.</p>
<p>Estos resultados se <strong>estimaron</strong> a partir de submuestras de <span class="math inline">\(N_c = 1000\)</span> estudiantes en Chile y <span class="math inline">\(N_d = 1000\)</span> estudiantes en Dinamarca. La tabla muestra que, por ejemplo, segùn los estadìsticos muestras los estudiantes más favorecidos en Chile obtuvieron un puntaje promedio en matemáticas de 470 puntos, con una desviación estándar de 70 puntos.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 34%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Cuartil Socioeconómico</th>
<th>Chile: <span class="math inline">\(\hat{\mu}\)</span> (<span class="math inline">\(s\)</span>), (N_c = 1000)</th>
<th>Dinamarca: <span class="math inline">\(\hat{\mu}\)</span> (<span class="math inline">\(s\)</span>), (N_d = 1000)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>25% Inferior (Desfavorecidos)</td>
<td><strong>369</strong> (85)</td>
<td><strong>450</strong> (80)</td>
</tr>
<tr class="even">
<td>Segundo Cuartil</td>
<td><strong>400</strong> (80)</td>
<td><strong>470</strong> (75)</td>
</tr>
<tr class="odd">
<td>Tercer Cuartil</td>
<td><strong>430</strong> (75)</td>
<td><strong>490</strong> (70)</td>
</tr>
<tr class="even">
<td>25% Superior (Favorecidos)</td>
<td><strong>470</strong> (70)</td>
<td><strong>510</strong> (65)</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Nota #1:</strong> Recuerda que cada cuartil representa <span class="math inline">\(1/4\)</span> de la muestra de cada país.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Nota #2:</strong> Estudios cienfíticos indican que el puntaje de un estudiante en la prueba PISA puede ser tratado como una manifestación una variable aleatoria que sigue una distribución <em>Lomax</em> (también conocida como Pareto tipo-II).</p>
</blockquote>
<p>I.1. Siguiendo el Teorema del Límite Central, caracteriza la distribución muestral del promedio de puntaje para el segundo cuartil socioeconómico en Chile. Dado que no conocemos los parámetros poblacionales usa su estimado muestral.</p>
<p><strong>Respuesta:</strong></p>
<p>Podemos utilizar el Teorema del Límite Central (TLC) para aproximar la distribución muestral del promedio de puntaje para el segundo cuartil socioeconómico en Chile.</p>
<p>Dado que cada cuartil representa <span class="math inline">\(\frac{1}{4}\)</span> de la muestra total en cada país, el tamaño de la submuestra para cada cuartil es:</p>
<p><span class="math display">\[N_{\text{cuartil}} = \frac{N_c}{4} = \frac{1000}{4} = 250\]</span></p>
<p>El TLC establece que, para muestras suficientemente grandes, la distribución muestral del promedio <span class="math inline">\(\bar{X}\)</span> se aproxima a una distribución normal, incluso si la población original no es normal (distribución Lomax en nuestro caso). Por lo tanto, podemos caracterizar la distribución muestral del promedio como:</p>
<p><span class="math display">\[\bar{X} \sim \text{Normal} \left( \hat{\mu}, \frac{s}{\sqrt{N_{\text{cuartil}}}} \right)\]</span></p>
<p>donde:</p>
<ul>
<li><p><span class="math inline">\(\hat{\mu} = 400\)</span> es el puntaje promedio muestral para el segundo cuartil socioeconómico en Chile,</p></li>
<li><p><span class="math inline">\(s = 80\)</span> es la desviación estándar muestral para este grupo,</p></li>
<li><p><span class="math inline">\(N_{\text{cuartil}} = 250\)</span> es el tamaño de la submuestra para el cuartil.</p></li>
</ul>
<p>Calculamos el error estándar del promedio <span class="math inline">\(SE_{\bar{X}}\)</span>:</p>
<p><span class="math display">\[SE_{\bar{X}} = \frac{s}{\sqrt{N_{\text{cuartil}}}} = \frac{80}{\sqrt{250}} \approx 5.06\]</span></p>
<p>Entonces, la distribución muestral del promedio de puntaje para el segundo cuartil socioeconómico en Chile es aproximadamente:</p>
<p><span class="math display">\[\bar{X} \sim \text{Normal} \left(400, 5.06 \right)\]</span></p>
<p>Esto significa que, bajo el TLC, podemos aproximar la distribución del promedio de puntajes del segundo cuartil en Chile con una distribución normal con media (400) y desviación estándar (5.06).</p>
<hr>
<p>I.2. Calcula un intervalo al 95% de confianza para el promedio puntaje promedio del cuartil socioeconómico más rico en Chile y otro para el puntaje promedio del cuartil socioeconómico más pobre en Dinamarca. Explica que significa cada intervalo de confianza.</p>
<p><strong>Respuesta:</strong></p>
<p>Para calcular un intervalo de confianza al 95% para el promedio de puntaje en cada grupo (el cuartil socioeconómico más rico en Chile y el cuartil socioeconómico más pobre en Dinamarca), utilizaremos la fórmula del intervalo de confianza para el promedio:</p>
<p><span class="math display">\[\text{IC}_{95\%} = \hat{\mu} \pm z \cdot \frac{s}{\sqrt{N_{\text{cuartil}}}}\]</span></p>
<p>donde:</p>
<ul>
<li><p><span class="math inline">\(\hat{\mu}\)</span> es el puntaje promedio muestral,</p></li>
<li><p><span class="math inline">\(s\)</span> es la desviación estándar muestral,</p></li>
<li><p><span class="math inline">\(N_{\text{cuartil}} = 250\)</span> (ya que cada cuartil representa <span class="math inline">\(\frac{1}{4}\)</span> de la muestra total de 1000 estudiantes en cada país),</p></li>
<li><p><span class="math inline">\(z\)</span> es el valor crítico para un nivel de confianza del 95%, que es aproximadamente 1.96.</p></li>
<li><p>Intervalo de confianza al 95% para el cuartil socioeconómico más rico en Chile:</p></li>
</ul>
<p>Para los estudiantes del cuartil superior en Chile:</p>
<ul>
<li><span class="math inline">\(\hat{\mu} = 470\)</span>,</li>
<li><span class="math inline">\(s = 70\)</span>.</li>
</ul>
<p>El error estándar es:</p>
<p><span class="math display">\[SE_{\bar{X}} = \frac{s}{\sqrt{N_{\text{cuartil}}}} = \frac{70}{\sqrt{250}} \approx 4.43\]</span></p>
<p>El intervalo de confianza al 95% es:</p>
<p><span class="math display">\[470 \pm 1.96 \cdot 4.43\]</span> <span class="math display">\[470 \pm 8.68 = (461.32, 478.68)\]</span></p>
<ul>
<li>Intervalo de confianza al 95% para el cuartil socioeconómico más pobre en Dinamarca:</li>
</ul>
<p>Para los estudiantes del cuartil inferior en Dinamarca:</p>
<ul>
<li><span class="math inline">\(\hat{\mu} = 450\)</span>,</li>
<li><span class="math inline">\(s = 80\)</span>.</li>
</ul>
<p>El error estándar es:</p>
<p><span class="math display">\[SE\_{\bar{X}} = \frac{s}{\sqrt{N_{\text{cuartil}}}} = \frac{80}{\sqrt{250}} \approx 5.06\]</span></p>
<p>El intervalo de confianza al 95% es:</p>
<p><span class="math display">\[450 \pm 1.96 \cdot 5.06\]</span></p>
<p><span class="math display">\[450 \pm 9.92 = (440.08, 459.92)\]</span></p>
<p>Cada intervalo de confianza proporciona un rango en el cual esperamos que se encuentre el verdadero promedio de puntaje en matemáticas para los respectivos grupos, con un nivel de confianza del 95%. Esto quiere decir que, si repitiéramos este proceso de muestreo muchas veces, aproximadamente el 95% de esos intervalos incluirían el verdadero promedio de puntaje para el grupo en cuestión.</p>
<hr>
<p>I.3. Calcula la probabilidad de que el promedio muestral del puntaje el cuartil socioeconómico más rico en Chile sobrestime el verdadero promedio en 20 puntos o más.</p>
<p><strong>Respuesta:</strong></p>
<p>Queremos calcular:</p>
<p><span class="math display">\[P(\bar{X} - \mu &gt; 20)\]</span></p>
<p>Dado que <span class="math inline">\(\bar{X} \sim \text{Normal}\left(\mu, \frac{s}{\sqrt{N_{\text{cuartil}}}}\right)\)</span>, con: - <span class="math inline">\(\mu = 470\)</span> (el verdadero promedio poblacional), - (s = 70) (desviación estándar de la muestra), - <span class="math inline">\(N\_{\text{cuartil}} = 250\)</span> (tamaño de la submuestra),</p>
<p>primero calculamos el error estándar del promedio:</p>
<p><span class="math display">\[SE\_{\bar{X}} = \frac{s}{\sqrt{N_{\text{cuartil}}}} = \frac{70}{\sqrt{250}} \approx 4.43\]</span></p>
<p>Ahora, reescribimos la probabilidad en términos de la variable normal estándar (Z):</p>
<p><span class="math display">\[P(\bar{X} - \mu &gt; 20) = P\left(\frac{\bar{X} - \mu}{SE_{\bar{X}}} &gt; \frac{20}{4.43}\right)\]</span></p>
<p>Calculamos el valor (z)-estándar:</p>
<p><span class="math display">\[z = \frac{20}{4.43} \approx 4.51\]</span></p>
<p>Finalmente, la probabilidad es:</p>
<p><span class="math display">\[P(Z &gt; 4.51)\]</span></p>
<p>Para (z = 4.51), la probabilidad es extremadamente baja, prácticamente cero. Esto significa que la probabilidad de que el promedio muestral sobrestime el verdadero promedio en 20 puntos o más es casi nula.</p>
<hr>
<p>I.4. Un político chileno del partido UTI afirma: “Nuestros estudiantes màs aventajados (socioeconómicamente) tienen un desempeño en matemáticas superior al de los estudiantes menos aventajados de paises socialistas como Dinamarca”. Desarrolla un test de hipótesis para testear esta afirmación con un nivel de significación del 5%.</p>
<p><strong>Respuesta:</strong></p>
<p>Para evaluar la afirmación del político chilenorealizaremos un test de hipótesis para diferencia de medias usando un nivel de significación del 5%.</p>
<ul>
<li><strong>Hipótesis nula</strong> <span class="math inline">\(H_0\)</span>: El promedio de puntaje en matemáticas de los estudiantes más favorecidos en Chile es igual al de los estudiantes menos favorecidos en Dinamarca.</li>
</ul>
<p><span class="math display">\[H_0: \mu_{\text{Chile, alto}} = \mu_{\text{Dinamarca, bajo}}\]</span></p>
<ul>
<li><strong>Hipótesis alternativa</strong> <span class="math inline">\(H_1\)</span>: El promedio de puntaje en matemáticas de los estudiantes más favorecidos en Chile es mayor que el de los estudiantes menos favorecidos en Dinamarca.</li>
</ul>
<p><span class="math display">\[H_1: \mu_{\text{Chile, alto}} &gt; \mu_{\text{Dinamarca, bajo}}\]</span></p>
<ul>
<li>Estadísticos de la Muestra</li>
</ul>
<p>Dado:</p>
<p>Para el cuartil socioeconómico superior en Chile:</p>
<ul>
<li><p>Puntaje promedio muestral, <span class="math inline">\(\hat{\mu}_{\text{Chile, alto}} = 470\)</span></p></li>
<li><p>Desviación estándar muestral, <span class="math inline">\(s_{\text{Chile, alto}} = 70\)</span></p></li>
<li><p>Tamaño de la submuestra, <span class="math inline">\(N_{\text{Chile, alto}} = 250\)</span></p></li>
</ul>
<p>Para el cuartil socioeconómico inferior en Dinamarca:</p>
<ul>
<li><p>Puntaje promedio muestral, <span class="math inline">\(\hat{\mu}_{\text{Dinamarca, bajo}} = 450\)</span></p></li>
<li><p>Desviación estándar muestral, <span class="math inline">\(s_{\text{Dinamarca, bajo}} = 80\)</span></p></li>
<li><p>Tamaño de la submuestra, <span class="math inline">\(N_{\text{Dinamarca, bajo}} = 250\)</span></p></li>
</ul>
<p><strong>Distribución Nula</strong></p>
<p>La distribución nula describe el comportamiento del estadístico de prueba bajo la suposición de que la hipótesis nula es verdadera. En este caso, asumimos que el verdadero promedio de puntaje en matemáticas de los estudiantes más aventajados en Chile es igual al de los estudiantes menos aventajados en Dinamarca, es decir, <span class="math inline">\(\mu_{\text{Chile, alto}} = \mu{\text{Dinamarca, bajo}}\)</span>.</p>
<p>Cuando (H_0) es verdadera, la diferencia en las medias muestrales <span class="math inline">\(\bar{X}_{\text{Chile, alto}} - \bar{X}_{\text{Dinamarca, bajo}}\)</span> sigue una distribución normal con media 0 y varianza dada por la suma de las varianzas de cada media muestral. Por lo tanto, la distribución nula de <span class="math inline">\(\bar{X}_{\text{Chile, alto}} - \bar{X}_{\text{Dinamarca, bajo}}\)</span> es:</p>
<p><span class="math display">\[\bar{X}*{*\text{Chile, alto}} - \bar{X}{\text{Dinamarca, bajo}} \sim \text{Normal} \left(0, \sqrt{\frac{s_{\text{Chile, alto}}^2}{N_{\text{Chile, alto}}} + \frac{s_{\text{Dinamarca, bajo}}^2}{N_{\text{Dinamarca, bajo}}}} \right)\]</span></p>
<p>Sustituyendo los valores:</p>
<ul>
<li>Para los estudiantes del cuartil superior en Chile:
<ul>
<li>Desviación estándar muestral, <span class="math inline">\(s_{\text{Chile, alto}} = 70\)</span>,</li>
<li>Tamaño de la muestra, <span class="math inline">\(N_{\text{Chile, alto}} = 250)\)</span>.</li>
</ul></li>
<li>Para los estudiantes del cuartil inferior en Dinamarca:
<ul>
<li>Desviación estándar muestral, <span class="math inline">\(s_{\text{Dinamarca, bajo}} = 80\)</span>,</li>
<li>Tamaño de la muestra, <span class="math inline">\(N_{\text{Dinamarca, bajo}} = 250\)</span>.</li>
</ul></li>
</ul>
<p>La varianza combinada es:</p>
<p><span class="math display">\[\text{Var}(\bar{X}*{*\text{Chile, alto}} - \bar{X}{\text{Dinamarca, bajo}}) = \frac{70^2}{250} + \frac{80^2}{250} = 19.6 + 25.6 = 45.2\]</span></p>
<p>Por lo tanto, el error estándar de la diferencia es:</p>
<p><span class="math display">\[\text{SE} = \sqrt{45.2} \approx 6.72\]</span></p>
<ul>
<li>Calcular el Estadístico de Prueba</li>
</ul>
<p>Dado que ambas muestras son grandes, podemos usar un <strong>test (Z) para dos muestras</strong>. El estadístico de prueba es:</p>
<p><span class="math display">\[Z = \frac{\hat{\mu}_{\text{Chile, alto}} - \hat{\mu}_{\text{Dinamarca, bajo}}}{\text{SE}}\]</span></p>
<p>Sustituyendo los valores:</p>
<p><span class="math display">\[Z = \frac{470 - 450}{6.72} \approx 2.98\]</span></p>
<ul>
<li>Determinar el Valor Crítico y la Región de Rechazo</li>
</ul>
<p>Con un nivel de significación de <span class="math inline">\(\alpha = 0.05\)</span> y un test unilateral, el valor crítico de (Z) para un nivel de confianza del 95% es aproximadamente <span class="math inline">\(Z_{0.05} = 1.645\)</span>.</p>
<section id="paso-3-comparar-el-estadístico-de-prueba-con-el-valor-crítico" class="level3">
<h3 class="anchored" data-anchor-id="paso-3-comparar-el-estadístico-de-prueba-con-el-valor-crítico">Paso 3: Comparar el Estadístico de Prueba con el Valor Crítico</h3>
<p>Dado que el estadístico (Z = 2.98) es mayor que el valor crítico de (1.645), rechazamos la hipótesis nula.</p>
<p>Conclusión con un nivel de significación del 5%, hay suficiente evidencia para rechazar la hipótesis nula y concluir que el promedio de puntaje en matemáticas de los estudiantes más favorecidos en Chile es, en términos estadísticos, significativamente mayor que el de los estudiantes menos favorecidos en Dinamarca.</p>
<hr>
<p>I.5. Teniendo en mente la afirmación del político chileno, compara los resultados obtenidos en I.2 e I.4. Explica las potenciales diferencias y similitudes entre ambos.</p>
<p><strong>Respuesta:</strong></p>
<p>Para comparar los enfoques de <strong>I.2</strong> e <strong>I.4</strong> y entender sus resultados en el contexto de la afirmación del político chileno, consideremos lo siguiente:</p>
<ul>
<li><p>Los intervalos de confianza en <strong>I.2</strong> fueron calculados a dos colas, lo que los hace más estrictos, ya que consideran diferencias en ambas direcciones. Este criterio conservador implica una sobreestimación implícita del error estándar en la comparación de los dos grupos, aumentando el rigor al requerir mayor separación para evitar la superposición.</p></li>
<li><p>En cambio, el test de hipótesis en <strong>I.4</strong> proporciona una comparación directa y precisa, enfocada solo en si el promedio de los estudiantes más aventajados en Chile es mayor que el de los menos aventajados en Dinamarca. Este enfoque unilateral permite evaluar la afirmación de manera más sensible y específica.</p></li>
<li><p>La falta de superposición en los intervalos de confianza en <strong>I.2</strong> refuerza la robustez del resultado obtenido en el test de hipótesis en <strong>I.4</strong>. Ambos métodos, aunque con enfoques diferentes, respaldan firmemente la afirmación del político chileno: el desempeño en matemáticas de los estudiantes más aventajados en Chile es significativamente superior al de los estudiantes menos aventajados en Dinamarca.</p></li>
</ul>
<hr>
<p><strong>Problema II.</strong></p>
<p>Un estudio epidemiológico fue llevado a cabo para evaluar la efectividad de una vacuna contra una enfermedad infecciosa en una comunidad de la Región Metropolitana. Los investigadores hicieron seguimiento durante un año a un grupo de personas, de las cuales algunas recibieron la vacuna como medida preventiva (grupo vacunado), mientras que otras no la recibieron (grupo de control). Los resultados muestran que en el grupo de control, <strong>7 de 10 personas</strong> contrajeron la enfermedad, mientras que <strong>3 no la contrajeron</strong>. Por otro lado, en el grupo vacunado, solo <strong>4 de 10 personas</strong> contrajeron la enfermedad, mientras que <strong>6 no la contrajeron</strong>.</p>
<p>La siguiente tabla resume los resultados</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Contrajo la enfermedad</th>
<th>No contrajo la enfermedad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Grupo Control</td>
<td>7</td>
<td>3</td>
</tr>
<tr class="even">
<td>Grupo Vacunado</td>
<td>4</td>
<td>6</td>
</tr>
</tbody>
</table>
<p>Aunque los resultados son preliminares y basados en una muestra pequeña, sugieren un posible beneficio de la vacunación en la reducción de la incidencia de la enfermedad en esta comunidad.</p>
<p>II.1 Testea la hipótesis de existe un beneficio de la vacunación en la reducción de la incidencia de la enfermedad. Trabaja al 95% de confianza.</p>
<p><strong>Respuesta:</strong></p>
<p>Para evaluar si la vacunación reduce la incidencia de la enfermedad, usaremos una prueba de diferencia de proporciones a una cola. Las hipótesis son:</p>
<ul>
<li><p><strong>Hipótesis nula (</strong><span class="math inline">\(H_0\)</span>): La vacunación no reduce la incidencia de la enfermedad, es decir, <span class="math inline">\(p_1 \leq p_2\)</span>.</p></li>
<li><p><strong>Hipótesis alternativa (</strong><span class="math inline">\(H_1\)</span>): La vacunación reduce la incidencia de la enfermedad, es decir, <span class="math inline">\(p_1 &gt; p_2\)</span>.</p></li>
</ul>
<p>Donde: - <span class="math inline">\(p_1\)</span> es la proporción de personas que contrajeron la enfermedad en el grupo de control. - <span class="math inline">\(p_2\)</span> es la proporción de personas que contrajeron la enfermedad en el grupo vacunado.</p>
<ul>
<li><p><strong>Datos de la muestra</strong></p>
<ul>
<li><strong>Grupo Control</strong>:
<ul>
<li>Personas que contrajeron la enfermedad: 7</li>
<li>Total de personas: <span class="math inline">\(n_1 = 10\)</span></li>
</ul></li>
<li><strong>Grupo Vacunado</strong>:
<ul>
<li>Personas que contrajeron la enfermedad: 4</li>
<li>Total de personas: <span class="math inline">\(n_2 = 10\)</span></li>
</ul></li>
</ul></li>
<li><p><strong>Proporciones de incidencia en cada grupo</strong></p>
<ul>
<li>Proporción en el grupo de control: <span class="math inline">\(p_1 = \frac{7}{10} = 0.7\)</span></li>
<li>Proporción en el grupo vacunado: <span class="math inline">\(p_2 = \frac{4}{10} = 0.4\)</span></li>
</ul></li>
<li><p><strong>Diferencia en proporciones observada</strong></p>
<ul>
<li>La diferencia en proporciones observada es <span class="math inline">\(\text{diferencia observada} = p_1 - p_2 = 0.7 - 0.4 = 0.3\)</span></li>
</ul></li>
<li><p><strong>Cálculo del error estándar bajo la hipótesis de diferencia cero</strong></p>
<p><span class="math display">\[\text{Error estándar} = \sqrt{\frac{p_1 \times (1 - p_1)}{n_1} + \frac{p_2 \times (1 - p_2)}{n_2}}\]</span></p>
<p>Sustituyendo los valores:</p>
<p><span class="math display">\[\text{Error estándar} = \sqrt{\frac{0.7 \times (1 - 0.7)}{10} + \frac{0.4 \times (1 - 0.4)}{10}}\]</span></p>
<p><span class="math display">\[= \sqrt{\frac{0.21}{10} + \frac{0.24}{10}}\]</span></p>
<p><span class="math display">\[= \sqrt{0.045} = 0.2121\]</span></p></li>
<li><p><strong>Cálculo del estadístico Z</strong></p></li>
</ul>
<p>Usamos Z porque el calculo del error estándar no conlleva pérdida de grados de libertad.</p>
<p><span class="math display">\[Z = \frac{\text{diferencia observada}}{\text{Error estándar}} = \frac{0.3}{0.2121} = 1.414\]</span></p>
<p>Luego, para una prueba de una cola (donde estamos interesados en si la incidencia en el grupo vacunado es menor), el valor p se calcula tomando el área bajo la curva normal para <span class="math inline">\(Z = 1.414\)</span>:</p>
<p><span class="math display">\[p = 1 - \text{P(Z ≤ 1.414)}  \approx 0.079\]</span></p>
<p>Es decir, dado el valor p de 0.079 es mayor que el nivel de significancia de 0.05, no tenemos suficiente evidencia para rechazar la hipótesis nula. Esto indica que no podemos concluir que la vacunación reduzca significativamente la incidencia de la enfermedad en esta comunidad.</p>
<hr>
<p>II.2 En este estudio se midió además la gravedad de los síntomas en una escala continua (de 0 a 100, donde 0 indica ausencia total de síntomas y 100 los síntomas más graves observados). Los resultados mostraron que el grupo vacunado presentó una media de severidad de síntomas de 30, mientras que el grupo de control presentó una media de 70, sugiriendo una posible reducción en la gravedad de la enfermedad en los vacunados.</p>
<p>En base a estos datos, testea la hipótesis de que existe un beneficio de la vacunación en la reducción de la severidad de los síntomas. Trabaja al 95% de confianza.</p>
<p>**Importante*: Considera 16 grados de libertad para la diferencia de medias (<span class="math inline">\(df=16\)</span>).</p>
<p>La siguiente tabla resume los resultados:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 30%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Media de severidad de síntomas</th>
<th><span class="math inline">\(\sum (x_i - \bar{x})^2\)</span></th>
<th><span class="math inline">\(n\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Grupo Control</td>
<td>70</td>
<td>1800</td>
<td>10</td>
</tr>
<tr class="even">
<td>Grupo Vacunado</td>
<td>30</td>
<td>900</td>
<td>10</td>
</tr>
</tbody>
</table>
<p><strong>Respuesta:</strong></p>
<p>Para evaluar si la vacunación reduce la severidad de los síntomas, realizaremos una prueba prueba<span class="math inline">\(t\)</span> para dos muestras independientes.</p>
<ul>
<li><p><strong>Hipótesis nula (</strong><span class="math inline">\(H_0\)</span>): No hay diferencia en la severidad de los síntomas entre los grupos, es decir, <span class="math inline">\(\mu_{\text{control}} = \mu_{\text{vacunado}}\)</span>.</p></li>
<li><p><strong>Hipótesis alternativa (</strong><span class="math inline">\(H_1\)</span>): La vacunación reduce la severidad de los síntomas, es decir, <span class="math inline">\(\mu_{\text{control}} &gt; \mu_{\text{vacunado}}\)</span>.</p></li>
</ul>
<p>Usando los datos de la tabla:</p>
<ul>
<li><strong>Grupo Control</strong>:
<ul>
<li>Media (<span class="math inline">\(\bar{x}_1\)</span>) = 70</li>
<li>Suma de residuos al cuadrado (<span class="math inline">\(\sum (x_i - \bar{x})^2\)</span>) = 1800</li>
<li>Tamaño de muestra (<span class="math inline">\(n_1\)</span>) = 10</li>
</ul></li>
<li><strong>Grupo Vacunado</strong>:
<ul>
<li>Media (<span class="math inline">\(\bar{x}_2\)</span>) = 30</li>
<li>Suma de residuos al cuadrado (<span class="math inline">\(\sum (x_i - \bar{x})^2\)</span>) = 900</li>
<li>Tamaño de muestra (<span class="math inline">\(n_2\)</span>) = 10</li>
</ul></li>
</ul>
<p>Varianza Muestral para cada grupo:</p>
<p>La varianza muestral (<span class="math inline">\(s^2\)</span>) se calcula como:</p>
<p><span class="math display">\[s^2 = \frac{\sum (x_i - \bar{x})^2}{n - 1}\]</span></p>
<ul>
<li><p><strong>Varianza del grupo control</strong>:</p>
<p><span class="math display">\[s_1^2 = \frac{1800}{10 - 1} = \frac{1800}{9} = 200\]</span></p></li>
<li><p><strong>Varianza del grupo vacunado</strong>:</p>
<p><span class="math display">\[s_2^2 = \frac{900}{10 - 1} = \frac{900}{9} = 100\]</span></p></li>
</ul>
<p>Luego, el estadístico<span class="math inline">\(t\)</span> es:</p>
<p><span class="math display">\[t = \frac{\bar{x}_1 - \bar{x}_2}{\sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}}\]</span></p>
<p><span class="math display">\[t = \frac{70 - 30}{\sqrt{\frac{200}{10} + \frac{100}{10}}} = \frac{40}{\sqrt{20 + 10}} = \frac{40}{\sqrt{30}} = \frac{40}{5.477} \approx 7.3\]</span></p>
<p>Al calcular el valor p asociado a un estadístico <span class="math inline">\(t=7.3\)</span> en una distribución <span class="math inline">\(t\)</span>-student con 16 grados de libertad en una prueba de una cola, obtenemos un valor extremadamente pequeño (cerca de 0.000001). Este resultados constituye evidencia fuerte contra la hipótesis nula, sugiriendo que la diferencia en la severidad de los síntomas entre los grupos es altamente significativa.</p>
<p>Dado que el valor del estadístico t calculado (aproximadamente 7.3) es mucho mayor que el valor crítico de 1.75, rechazamos la hipótesis nula. Esto proporciona evidencia estadísticamente significativa de que la vacunación reduce la severidad de los síntomas en esta muestra.</p>
<p>Por lo tanto, podemos concluir, con un nivel de confianza del 95%, que la vacunación tiene un efecto beneficioso en la reducción de la severidad de los síntomas de la enfermedad.</p>
<hr>
<p>II.3. Un laboratorio desea repetir este experimento, garantizando que, con un nivel de confianza del 95%, el intervalo de confianza para la proporción de personas en cada uno de los grupos tenga un margen de error de, como máximo, <span class="math inline">\(\pm 0.01\)</span> (1 punto porcentual). Suponiendo que tanto el grupo de tratamiento como el de control tendrán el mismo tamaño, calcula el tamaño de muestra necesario para cada grupo para lograr este margen de error.</p>
<p><strong>Respuesta:</strong></p>
<p>Para calcular el tamaño de la muestra necesario para cada grupo con un margen de error de<span class="math inline">\(\pm 0.01\)</span> y un nivel de confianza del 95%, utilizamos la fórmula del tamaño de muestra para una proporción.</p>
<p><span class="math display">\[n = \frac{Z^2 \cdot p \cdot (1 - p)}{E^2}\]</span></p>
<p>donde:</p>
<p>-<span class="math inline">\(Z\)</span> es el valor crítico para el nivel de confianza del 95%, aproximadamente<span class="math inline">\(1.96\)</span>.</p>
<p>-<span class="math inline">\(p\)</span> es una estimación de la proporción en la población. Para maximizar el tamaño de la muestra (considerando la máxima varianza), tomamos<span class="math inline">\(p = 0.5\)</span>.</p>
<p>-<span class="math inline">\(E\)</span> es el margen de error deseado, en este caso<span class="math inline">\(E = 0.01\)</span>.</p>
<p>Sustituyendo los valores:</p>
<ol type="1">
<li><strong>Valor crítico</strong> <span class="math inline">\(Z\)</span>: Para un nivel de confianza del 95%, <span class="math inline">\(Z = 1.96\)</span>.</li>
<li><strong>Proporción estimada</strong> <span class="math inline">\(p\)</span>: Usamos <span class="math inline">\(p = 0.5\)</span> para maximizar la varianza.</li>
<li><strong>Margen de error</strong> <span class="math inline">\(E\)</span>: <span class="math inline">\(E = 0.01\)</span>.</li>
</ol>
<p><span class="math display">\[n = \frac{(1.96)^2 \cdot 0.5 \cdot (1 - 0.5)}{(0.01)^2} = \frac{3.8416 \cdot 0.25}{0.0001} = 9604\]</span></p>
<p>Por tanto, para alcanzar un margen de error de<span class="math inline">\(\pm 0.01\)</span> con un nivel de confianza del 95%, se necesita un tamaño de muestra de <strong>9604 participantes en cada grupo</strong> (tratamiento y control), lo que da un total de <strong>19208 participantes</strong> para el experimento completo.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>