---
title: "Probabilidad e Inferencia Estadística"
subtitle: "#11: Estimación de Intervalos"
author: "<br> Mauricio Bucca <br> [github.com/mebucca](https://github.com/mebucca) <br> mebucca@uc.cl"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["gentle-r.css","xaringan-themer.css"]
    df_print: default
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: true
      slideNumberFormat: "%current%"
editor_options: 
  chunz_output_type: console
---  
class: inverse, center, middle

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(tidyverse)
library(xaringanthemer)
style_duo_accent(primary_color ="#708090", secondary_color ="#008080",
                 background_color = "#f8f7f3",
                 header_font_google = google_font("Archivo"),
                 text_font_google   = google_font("Inconsolata"), 
                 link_color= "#DAA520"

)
```

# Estimación de Intervalos


---
##Distribución Muestral


--

Si $\hat{\beta}$ es un estimador definido como $\hat{\beta}: f(\text{datos})$, la **distribución muestral** de $\hat{\beta}$ es la distribución de probabilidad de todos los valores posibles que $\hat{\beta}$ puede tomar, calculados a partir de todas las posibles muestras de un tamaño dado $n$, tomadas a partir de la misma población o generados por el mismo proceso. 

<br>
--



.bold[Paso a paso,]

<br>

--

- Tomamos todas las posibles muestras $m_{i}: \{ X_1, X_2, ..., X_n \}$ de un tamaño  
dado $n$, generados por el mismo proceso (o población).

--

- En cada $m_{i}$ aplicamos nuestro estimador y obtenemos $\hat{\beta}_{i}$. Formalmente, $f(m_{i}) = \hat{\beta}_{i}$.

--

- La .bold[distribución muestral] del estimador $\hat{\beta}$ refiere a la distribución de la colección obtenida de estimados $\hat{\beta}_{i}$.

--

- Como toda distribución de probabilidades, la .bold[distribución muestral] indica la probabilidad de obtener cada valor posible al aplicar el estimador $\hat{\beta}$.




---
class: inverse, center, middle


##Hasta la próxima clase. Gracias!

<br>
Mauricio Bucca <br>
https://mebucca.github.io/ <br>
github.com/mebucca




